
spring:
  application:
    name: medical-start
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /
      suffix: .html
  datasource:
    username: root
    password: tiger
    url: jdbc:mysql://127.0.0.1:3306/medical?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/static/

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.medical.entity
  configuration:
    map-underscore-to-camel-case: true